# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-10 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigOfServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(blank=True, max_length=255, verbose_name='\u0413\u0440\u0443\u043f\u043f\u0430')),
                ('key', models.CharField(max_length=255, unique=True, verbose_name='\u041f\u0430\u0440\u0430\u043c\u0435\u0442\u0440')),
                ('value', models.CharField(blank=True, max_length=1024, verbose_name='\u0417\u043d\u0430\u0447\u0435\u043d\u0438\u0435')),
                ('type_of_value', models.IntegerField(choices=[(1, 'int'), (2, 'float'), (0, '\u0441\u0442\u0440\u043e\u043a\u0430')], default=0, verbose_name='\u0422\u0438\u043f')),
                ('changed_on', models.DateTimeField(auto_now=True, verbose_name='\u0414\u0430\u0442\u0430 \u0438\u0437\u043c\u0435\u043d\u0435\u043d\u0438\u044f')),
                ('description', models.CharField(blank=True, max_length=1024, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
            ],
            options={
                'ordering': ('group', 'key'),
                'verbose_name': '\u041f\u0430\u0440\u0430\u043c\u0435\u0442\u0440',
                'verbose_name_plural': '\u041f\u0430\u0440\u0430\u043c\u0435\u0442\u0440\u044b',
            },
        ),
    ]
